### ISSUE TITLE
Connect sensor data to charts

### ISSUE THREAD

**Issue by tejashah88** [DVC-Viking-Robotics/webapp#24]
The sensor dashboard currently displays dummy data and should be ideally pulling the data from the robot via sockets.
- [x] transmit sensor data from server to client via websocket.
- [x] translate data into the charts.js API for data visualization

**Comment by 2bndy5** [comment]
Looks like the call to trigger getting the sensor data via the socket `sensorDoF` (emitted from sockets.py) got lost or deleted during refactoring crusade or even earlier. We have to patch it back in. Currently, there's no websocket declaration on the sensors.html page. Also sensor-data.js was being used for getting both GPS and IMU data, but now its only good for GPS (the heading data is commented out).

**Comment by tejashah88** [comment]
If you mean from `sockets.py`, it wasn't ever deleted: https://github.com/DVC-Viking-Robotics/webapp/blame/nondrive-R2D2/webapp/sockets.py#L147. As for the heading code, I commented it out for now until you had a stable implementation ready.

**Comment by 2bndy5** [comment]
that line is the programmed response to a socket call from `sensor-data.js` file related to the socket called `sensorDoF`, but the instigating function from `sensor-data.js` is gone (meaning the `sensorDoF` socket is never being utilized). And BTW @tejashah88 COMMENTS!!! I'm not sure how to inject the data into your charts. Additionally I think the `raw-data` element id should be renamed `imu-data` (or something a little more specific) since the raw data actually exists on the sensor only (raw data is without proper units; displayed data has conceivable units)

**Comment by 2bndy5** [comment]
IMU sensor data is getting to the `sensors.html` page, but not getting injected into the charts. 
see the changes in my [chart-data branch](https://github.com/DVC-Viking-Robotics/webapp/tree/chart-data)
