### ISSUE TITLE
webapp needs a shutdown server and shutdown/reboot raspi option in the GUI

### ISSUE THREAD

**Issue by 2bndy5** [DVC-Viking-Robotics/webapp#39]
We should stop using keyboard interrupts for many reasons; the most important: Its not kind to the SPI, I2C, and Serial libraries using our hardware peripherals. A badly timed keyboard interrupt can require a system restart to release the software locks on the aforementioned protocol's hardware buses.

- [ ] Shutdown Server button
- [ ] Shutdown/Restart System button

**Comment by rbretmounet** [comment]
SUMMARY:
Added a power-off drop-down menu that shows three options: Shutdown Server, Shutdown Robot, and Restart Robot. 
- Shutdown server redirects to function 'shutdown_server' in 'routes.py' which requires a login and closes the socket.
- Shutdown Robot in theory (since I don't have a rasp pi to test on) also redirects to function 'shutdown_robot' in 'routes.py' which requires a login should and execute 'sudo shutdown -h now' which results in the rasp pi to shutdown. 
- Restart Robot in theory (again since I don't have a rasp pi to test on) should also redirect to a function  'restart()' in 'routes.py' which requires a login and execute 'sudo reboot' which reboots the rasp pi.

IMPORTANT NOTES:
- Issues may arise when trying to execute a sudo command such as is requiring a username and password for executing the command. If so solution may be to run on an admin account.
- For shutdown and reboot buttons for rasp pi only works if webapp is ran off the rasp pi that controls the robot.
 
FUTURE UPDATES:

- If we decide to run webapp off a cloud-based server which communicates to the rasp pi over wifi we would need to change code to work with so.
- If any issues arise from sudo or not being able to execute commands for shutdown and reboot.
